# Generated by Django 5.2.12 on 2026-04-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_comment='网站地址', max_length=2048)),
                ('title', models.CharField(db_comment='网站标题', max_length=200)),
                ('description', models.TextField(blank=True, db_comment='简要描述', null=True)),
                ('favicon_url', models.CharField(blank=True, db_comment='网站图标地址', max_length=512, null=True)),
                ('is_domestic', models.IntegerField(db_comment='地域：1 = 国内，0 = 国外')),
                ('site_scale', models.CharField(db_comment='网站规模', max_length=10)),
                ('is_active', models.IntegerField(db_comment='是否可访问')),
                ('is_favorite', models.IntegerField(db_comment='收藏星标')),
                ('visit_count', models.PositiveIntegerField(db_comment='点击次数')),
                ('last_visit', models.DateTimeField(blank=True, db_comment='最近访问时间', null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'bookmarks',
                'db_table_comment': '网站书签',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookmarkTags',
            fields=[
                ('pk', models.CompositePrimaryKey('bookmark_id', 'tag_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bookmark_tags',
                'db_table_comment': '书签与标签的关联表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='标签名称，如 博客、工具、AI', max_length=50, unique=True)),
                ('slug', models.CharField(db_comment='URL 友好标识', max_length=50, unique=True)),
                ('color', models.CharField(blank=True, db_comment='标签颜色（HEX）', max_length=7, null=True)),
            ],
            options={
                'db_table': 'tags',
                'db_table_comment': '书签标签',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserBookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_bookmarks',
                'db_table_comment': '用户与书签的关联表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_tags',
                'db_table_comment': '用户与标签的关联表',
                'managed': False,
            },
        ),
    ]
